### ISSUE TITLE
#Pregunta clie_telefono

### ISSUE THREAD

**Issue by juanstepanenko** [roavakian/PagoAgilGDD#2]
clie_telefono no esta en la tabla maestra, como hacemos?

**Comment by roavakian** [comment]
Sacar el default, que quede en null ahora y que para los proximos sea obligatorio

**Comment by solborbore** [comment]
sacado el default, falta chequear bien que no se cree sin telefono

**Comment by roavakian** [comment]
@solborbore hacerlo, si queda en null agregarlo a #documento

**Comment by roavakian** [comment]
@solborbore se cierra?

**Comment by solborbore** [comment]
Dejar todo en null, el usuario también
