### ISSUE TITLE
Pregunta pago id

### ISSUE THREAD

**Issue by roavakian** [roavakian/PagoAgilGDD#3]
Tengo un pago con un id autogenerado pero cargo pagos anteriores, supongamos que tengo un pago 16, cuando el autogenerado me de 16... qué pasa?
(pago_id primary key)

**Comment by juanstepanenko** [comment]
Se pisa lo viejo, igusl lo voy a preguntar

**Comment by roavakian** [comment]
Dijo el ayudante que se pisa con el autogenerado, osea lo hace solo el motor, ni siquiera hay que decirle asigname acá pero que deberiamos guardar provisoriamente los id actuales por un tema de si alguna entidad se relaciona con ESE id como para no perderlo. Una vez que está todo relacionado se pueden borrar esos provisorios.
