### ISSUE TITLE
Si una sucu se deshabilita qué pasa con los cobradores?

### ISSUE THREAD

**Issue by roavakian** [roavakian/PagoAgilGDD#46]

**Comment by solborbore** [comment]
ahora lo agrego, que le saque la sucursal a los usuarios. Eso lo hago con los roles

**Comment by roavakian** [comment]
Y al documento!! @solborbore

**Comment by solborbore** [comment]
hace falta eliminarselo? total cuando elige con que rol o sucursal iniciar, estos tienen que estar habilitados. cuando vuelven a habiltar la sucursal, el usuario la tiene que tener disponible? habria que dejarselas entonces, pero que no la puedan abrir
